/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yCfvWFvWDDO
 */
import Link from "next/link";
import { Button } from "@/components/ui/button";

const Header = () => {
  return (
    <header className="flex items-center h-16 px-4 w-full md:px-36 drop-shadow-md border-b ">
      <Link className="mr-6" href="#">
        Business Card Generator
      </Link>
      <div className="ml-auto flex gap-2">
        <Link href={"./login"}>
          <Button variant="outline">Sign in</Button>
        </Link>
        <Link href={"./signup"}>
          <Button>Sign Up</Button>
        </Link>
      </div>
    </header>
  );
};
export default Header;
